import os
from abc import ABC, abstractmethod
from typing import AsyncIterator


class LLMProvider(ABC):
    @abstractmethod
    async def generate_stream(self, prompt: str) -> AsyncIterator[str]:
        """Stream tokens as they are generated by the model."""
        pass

    @staticmethod
    def load(config: dict = None) -> "LLMProvider":
        """Factory method to load the requested LLM provider dynamically.
        Supports: OpenAI, Groq, Ollama, DeepSeek, OpenRouter, GLM, local vLLM, or Mock.
        """
        config = config or {}
        provider = config.get("provider") or os.environ.get("LLM_PROVIDER")

        # Check if any LLM API keys or local endpoint env vars are set
        has_env_key = any(
            os.environ.get(k)
            for k in [
                "OPENAI_API_KEY",
                "GROQ_API_KEY",
                "DEEPSEEK_API_KEY",
                "OPENROUTER_API_KEY",
                "GLM_API_KEY",
                "OLLAMA_HOST",
                "LLM_API_BASE",
                "OPENAI_API_BASE",
            ]
        )

        if provider == "mock" or (
            not provider
            and not has_env_key
            and not config.get("api_key")
            and not config.get("api_base")
        ):
            from .mock import MockLLM

            return MockLLM(config)

        # Default to flexible OpenAI-compatible multi-provider implementation
        from .glm import GLM5Provider

        return GLM5Provider(config)
